import type { Person } from '../../shared/puzzle';

// Profession -> [male, female] emoji, ported verbatim from the live bundle.
const FACES: Record<string, [string, string]> = {
  police: ['👮‍♂️', '👮‍♀️'],
  cop: ['👮‍♂️', '👮‍♀️'],
  detective: ['🕵️‍♂️', '🕵️‍♀️'],
  sleuth: ['🕵️‍♂️', '🕵️‍♀️'],
  spy: ['🕵️‍♂️', '🕵️‍♀️'],
  guard: ['💂‍♂️', '💂‍♀️'],
  builder: ['👷‍♂️', '👷‍♀️'],
  farmer: ['👨‍🌾', '👩‍🌾'],
  cook: ['👨‍🍳', '👩‍🍳'],
  doctor: ['👨‍⚕️', '👩‍⚕️'],
  secretary: ['👨‍💼', '👩‍💼'],
  clerk: ['👨‍💼', '👩‍💼'],
  scientist: ['👨‍🔬', '👩‍🔬'],
  programmer: ['👨‍💻', '👩‍💻'],
  coder: ['👨‍💻', '👩‍💻'],
  singer: ['👨‍🎤', '👩‍🎤'],
  caroler: ['👨‍🎤', '👩‍🎤'],
  teacher: ['👨‍🏫', '👩‍🏫'],
  painter: ['👨‍🎨', '👩‍🎨'],
  firefighter: ['👨‍🚒', '👩‍🚒'],
  pilot: ['👨‍✈️', '👩‍✈️'],
  astronaut: ['👨‍🚀', '👩‍🚀'],
  judge: ['👨‍⚖️', '👩‍⚖️'],
  mechanic: ['👨‍🔧', '👩‍🔧'],
  mech: ['👨‍🔧', '👩‍🔧'],
  student: ['👨‍🎓', '👩‍🎓'],
  clown: ['🤡', '🤡'],
  witch: ['🧙', '🧙‍♀️'],
  vampire: ['🧛‍♂️', '🧛‍♀️'],
  pumpkin: ['🎃', '🎃'],
  zombie: ['🧟', '🧟'],
  bat: ['🦇', '🦇'],
  wolf: ['🐺', '🐺'],
  ghost: ['👻', '👻'],
  skeleton: ['💀', '💀'],
  ninja: ['🥷', '🥷'],
  superhero: ['🦸‍♂️', '🦸'],
  bride: ['👰', '👰'],
  santa: ['🎅', '🤶'],
  snowman: ['⛄️', '⛄️'],
  snowboarder: ['🏂', '🏂'],
  skier: ['⛷️', '⛷️'],
  reindeer: ['🦌', '🦌'],
  koala: ['🐨', '🐨'],
  bear: ['🐻', '🐻'],
  alien: ['👽', '👽'],
  elephant: ['🐘', '🐘'],
  cake: ['🎂', '🎂'],
  princess: ['👸', '👸'],
  bunny: ['🐰', '🐰'],
  robot: ['🤖', '🤖'],
  android: ['🤖', '🤖'],
  monkey: ['🐵', '🐵'],
  squirrel: ['🐿️', '🐿️'],
  leopard: ['🐆', '🐆'],
  cheetah: ['🐆', '🐆'],
  owl: ['🦉', '🦉'],
  fish: ['🐟', '🐟'],
  fox: ['🦊', '🦊'],
  chicken: ['🐣', '🐣'],
  sheep: ['🐑', '🐑'],
  alligator: ['🐊', '🐊'],
  crocodile: ['🐊', '🐊'],
  dolphin: ['🐬', '🐬'],
  woodchuck: ['🦫', '🦫'],
  sloth: ['🦥', '🦥'],
  snail: ['🐌', '🐌'],
  tortoise: ['🐢', '🐢'],
  bug: ['🐛', '🐛'],
  eagle: ['🦅', '🦅'],
  dog: ['🐶', '🐶'],
  mouse: ['🐭', '🐭'],
  pig: ['🐷', '🐷'],
  cat: ['🐈', '🐈'],
  horse: ['🐴', '🐴'],
};

/**
 * Newer puzzle files carry the emoji scraped from the source bundle, so new
 * professions render without code changes; the table covers older files.
 */
export function faceFor(person: Pick<Person, 'profession' | 'gender' | 'face'>): string {
  if (person.face) return person.face;
  const entry = FACES[person.profession];
  if (!entry) return '😬'; // the real renderer's unknown-profession fallback
  return entry[person.gender === 'female' ? 1 : 0];
}
